## Reference

[1] [超簡單台股每日爬蟲教學](https://www.finlab.tw/%E8%B6%85%E7%B0%A1%E5%96%AE%E5%8F%B0%E8%82%A1%E6%AF%8F%E6%97%A5%E7%88%AC%E8%9F%B2%E6%95%99%E5%AD%B8/)

***


# pybacktest 框架介紹 - MA 策略回測


 - [pybacktest](https://github.com/ematvey/pybacktest) 是一個基於 pandas 的 vectorized 回測框架
 
 
 - 這個框架可能不太適合更專業的回測需求，但剛好適合我們練習需求，讓我們看看怎麼用 pybacktest 來回測一個簡單的 MA 策略。

## MA Strategy

主要的想法是：

 - 計算兩個移動平均線，一條是長線，用來捕捉長期趨勢，一條是短線，用來捕捉短期趨勢。
 
 
 - 當短線從下方突破長線，則代表短期向上動能強，則我們買進。
 
 
 - 而短線從上方突破長線，則代表短期向下動能強，則我們賣出。

In [25]:
# loading library and dataset

import pandas as pd
import numpy as np
import sqlite3

db = sqlite3.connect('TWstock_2')
tsmc = pd.read_sql(con = db, sql = 'SELECT * FROM "2330"')

In [26]:
tsmc.head()

,index,證券名稱,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比,Date
0,409,台積電,"33,688,187","12,535","8,717,053,470",260.00,260.00,258.00,259.00,-,6.0,259.00,397,259.50,555,19.13,2019-05-06 00:00:00
1,409,台積電,"25,686,126","8,339","6,719,199,455",259.50,263.00,259.00,262.50,+,3.5,262.50,33,263.00,854,19.39,2019-05-07 00:00:00
2,409,台積電,"25,902,364","7,905","6,750,083,504",260.00,261.50,259.50,260.00,-,2.5,260.00,"3,639",260.50,51,19.20,2019-05-08 00:00:00
3,409,台積電,"34,166,574","10,995","8,798,140,796",259.50,259.50,256.00,256.50,-,3.5,256.50,396,257.00,6,18.94,2019-05-09 00:00:00
4,409,台積電,"18,868,212","8,009","4,844,594,484",257.00,259.00,255.00,256.00,-,0.5,256.00,"2,305",256.50,27,18.91,2019-05-10 00:00:00

### 整理資料


根據官方教學

 - pybacktest 預設接受 pandas.DataFrame 格式
 
 
 - 索引值為時間，columns 則為 O,H,L,C，所以我們把格式整理為需要的形式。
 
 
 - O(Open), H(High), L(Low), C(Close)

In [27]:
# clearning data
tsmc.index = tsmc['Date']
tsmc = tsmc[["開盤價","最高價","最低價","收盤價"]]
tsmc.columns = ["O","H","L","C"]
cols = tsmc.columns
tsmc[cols] = tsmc[cols].apply(pd.to_numeric, errors='coerce')

In [28]:
tsmc.head()

                         O      H      L      C
Date
2019-05-06 00:00:00  260.0  260.0  258.0  259.0
2019-05-07 00:00:00  259.5  263.0  259.0  262.5
2019-05-08 00:00:00  260.0  261.5  259.5  260.0
2019-05-09 00:00:00  259.5  259.5  256.0  256.5
2019-05-10 00:00:00  257.0  259.0  255.0  256.0

In [1]:
#載入pybacktest
import pybacktest

ModuleNotFoundError: No module named 'pybacktest'